// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var AttributeType = []string{
	"minecraft:boolean",
	"minecraft:tri_state",
	"minecraft:float",
	"minecraft:angle_degrees",
	"minecraft:rgb_color",
	"minecraft:argb_color",
	"minecraft:moon_phase",
	"minecraft:activity",
	"minecraft:bed_rule",
	"minecraft:particle",
	"minecraft:ambient_particles",
	"minecraft:background_music",
	"minecraft:ambient_sounds",
}
