// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var DialogType = []string{
	"minecraft:notice",
	"minecraft:server_links",
	"minecraft:dialog_list",
	"minecraft:multi_action",
	"minecraft:confirmation",
}
