// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var DialogActionType = []string{
	"minecraft:open_url",
	"minecraft:run_command",
	"minecraft:suggest_command",
	"minecraft:show_dialog",
	"minecraft:change_page",
	"minecraft:copy_to_clipboard",
	"minecraft:custom",
	"minecraft:dynamic/run_command",
	"minecraft:dynamic/custom",
}
