// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var DialogType = []string{
	"minecraft:notice",
	"minecraft:server_links",
	"minecraft:dialog_list",
	"minecraft:multi_action",
	"minecraft:confirmation",
}
