// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var EnchantmentValueEffectType = []string{
	"minecraft:add",
	"minecraft:all_of",
	"minecraft:multiply",
	"minecraft:remove_binomial",
	"minecraft:exponential",
	"minecraft:set",
}
