// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var EnchantmentProviderType = []string{
	"minecraft:by_cost",
	"minecraft:by_cost_with_difficulty",
	"minecraft:single",
}
