// Code generated by tools/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var EnchantmentLevelBasedValueType = []string{
	"minecraft:clamped",
	"minecraft:fraction",
	"minecraft:levels_squared",
	"minecraft:linear",
	"minecraft:exponent",
	"minecraft:lookup",
}
