// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var EntitySubPredicateType = []string{
	"minecraft:lightning",
	"minecraft:fishing_hook",
	"minecraft:player",
	"minecraft:slime",
	"minecraft:raider",
	"minecraft:sheep",
}
