// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var EntitySubPredicateType = []string{
	"minecraft:lightning",
	"minecraft:fishing_hook",
	"minecraft:player",
	"minecraft:slime",
	"minecraft:raider",
	"minecraft:sheep",
}
