// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var FloatProviderType = []string{
	"minecraft:constant",
	"minecraft:uniform",
	"minecraft:clamped_normal",
	"minecraft:trapezoid",
}
