// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var Fluid = []string{
	"minecraft:empty",
	"minecraft:flowing_water",
	"minecraft:water",
	"minecraft:flowing_lava",
	"minecraft:lava",
}
