// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var HeightProviderType = []string{
	"minecraft:constant",
	"minecraft:uniform",
	"minecraft:biased_to_bottom",
	"minecraft:very_biased_to_bottom",
	"minecraft:trapezoid",
	"minecraft:weighted_list",
}
