// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var InputControlType = []string{
	"minecraft:boolean",
	"minecraft:number_range",
	"minecraft:single_option",
	"minecraft:text",
}
