// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var IntProviderType = []string{
	"minecraft:constant",
	"minecraft:uniform",
	"minecraft:biased_to_bottom",
	"minecraft:clamped",
	"minecraft:weighted_list",
	"minecraft:clamped_normal",
}
