// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var LootPoolEntryType = []string{
	"minecraft:empty",
	"minecraft:item",
	"minecraft:loot_table",
	"minecraft:dynamic",
	"minecraft:tag",
	"minecraft:slots",
	"minecraft:alternatives",
	"minecraft:sequence",
	"minecraft:group",
}
