// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var LootNumberProviderType = []string{
	"minecraft:constant",
	"minecraft:uniform",
	"minecraft:binomial",
	"minecraft:score",
	"minecraft:storage",
	"minecraft:enchantment_level",
}
