// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var NumberFormatType = []string{
	"minecraft:blank",
	"minecraft:styled",
	"minecraft:fixed",
}
