// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var RecipeType = []string{
	"minecraft:crafting",
	"minecraft:smelting",
	"minecraft:blasting",
	"minecraft:smoking",
	"minecraft:campfire_cooking",
	"minecraft:stonecutting",
	"minecraft:smithing",
}
