// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var RecipeDisplay = []string{
	"minecraft:crafting_shapeless",
	"minecraft:crafting_shaped",
	"minecraft:furnace",
	"minecraft:stonecutter",
	"minecraft:smithing",
}
