// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var RuleTest = []string{
	"minecraft:always_true",
	"minecraft:block_match",
	"minecraft:blockstate_match",
	"minecraft:tag_match",
	"minecraft:random_block_match",
	"minecraft:random_blockstate_match",
}
