// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var RuleBlockEntityModifier = []string{
	"minecraft:clear",
	"minecraft:passthrough",
	"minecraft:append_static",
	"minecraft:append_loot",
}
