// Code generated by tools/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var SlotSourceType = []string{
	"minecraft:group",
	"minecraft:filtered",
	"minecraft:limit_slots",
	"minecraft:slot_range",
	"minecraft:contents",
	"minecraft:empty",
}
