// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var SlotSourceType = []string{
	"minecraft:group",
	"minecraft:filtered",
	"minecraft:limit_slots",
	"minecraft:slot_range",
	"minecraft:contents",
	"minecraft:empty",
}
