// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var SlotDisplay = []string{
	"minecraft:empty",
	"minecraft:any_fuel",
	"minecraft:item",
	"minecraft:item_stack",
	"minecraft:tag",
	"minecraft:smithing_trim",
	"minecraft:with_remainder",
	"minecraft:composite",
}
