// Code generated by tools/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var SpawnConditionType = []string{
	"minecraft:structure",
	"minecraft:moon_brightness",
	"minecraft:biome",
}
