// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var TestEnvironmentDefinitionType = []string{
	"minecraft:all_of",
	"minecraft:game_rules",
	"minecraft:time_of_day",
	"minecraft:weather",
	"minecraft:function",
}
