// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var TestEnvironmentDefinitionType = []string{
	"minecraft:all_of",
	"minecraft:game_rules",
	"minecraft:time_of_day",
	"minecraft:weather",
	"minecraft:function",
}
