// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var TicketType = []string{
	"minecraft:player_spawn",
	"minecraft:spawn_search",
	"minecraft:dragon",
	"minecraft:player_loading",
	"minecraft:player_simulation",
	"minecraft:forced",
	"minecraft:portal",
	"minecraft:ender_pearl",
	"minecraft:unknown",
}
