// Code generated by tools/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var VillagerType = []string{
	"minecraft:desert",
	"minecraft:jungle",
	"minecraft:plains",
	"minecraft:savanna",
	"minecraft:snow",
	"minecraft:swamp",
	"minecraft:taiga",
}
