// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var WorldgenCarver = []string{
	"minecraft:cave",
	"minecraft:nether_cave",
	"minecraft:canyon",
}
