// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var WorldgenBlockStateProviderType = []string{
	"minecraft:simple_state_provider",
	"minecraft:weighted_state_provider",
	"minecraft:noise_threshold_provider",
	"minecraft:noise_provider",
	"minecraft:dual_noise_provider",
	"minecraft:rotated_block_provider",
	"minecraft:randomized_int_state_provider",
}
