// Code generated by tools/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var WorldgenBiomeSource = []string{
	"minecraft:fixed",
	"minecraft:multi_noise",
	"minecraft:checkerboard",
	"minecraft:the_end",
}
