// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var WorldgenFeatureSizeType = []string{
	"minecraft:two_layers_feature_size",
	"minecraft:three_layers_feature_size",
}
