// Code generated by tools/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var WorldgenPoolAliasBinding = []string{
	"minecraft:random",
	"minecraft:random_group",
	"minecraft:direct",
}
