// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var WorldgenChunkGenerator = []string{
	"minecraft:noise",
	"minecraft:flat",
	"minecraft:debug",
}
