// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var WorldgenStructurePoolElement = []string{
	"minecraft:single_pool_element",
	"minecraft:list_pool_element",
	"minecraft:feature_pool_element",
	"minecraft:empty_pool_element",
	"minecraft:legacy_single_pool_element",
}
