// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var WorldgenPoolAliasBinding = []string{
	"minecraft:random",
	"minecraft:random_group",
	"minecraft:direct",
}
