// Code generated by tools/gen_registryid.go from 1.21.11/registries.json; DO NOT EDIT.

package registryid

var WorldgenStructurePlacement = []string{
	"minecraft:random_spread",
	"minecraft:concentric_rings",
}
