// Code generated by "stringer -type ServerboundPacketID"; DO NOT EDIT.

package packetid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerboundLoginHello-0]
	_ = x[ServerboundLoginKey-1]
	_ = x[ServerboundLoginCustomQueryAnswer-2]
	_ = x[ServerboundLoginLoginAcknowledged-3]
	_ = x[ServerboundLoginCookieResponse-4]
	_ = x[ServerboundStatusStatusRequest-0]
	_ = x[ServerboundStatusPingRequest-1]
	_ = x[ServerboundConfigClientInformation-0]
	_ = x[ServerboundConfigCookieResponse-1]
	_ = x[ServerboundConfigCustomPayload-2]
	_ = x[ServerboundConfigFinishConfiguration-3]
	_ = x[ServerboundConfigKeepAlive-4]
	_ = x[ServerboundConfigPong-5]
	_ = x[ServerboundConfigResourcePack-6]
	_ = x[ServerboundConfigSelectKnownPacks-7]
	_ = x[ServerboundConfigCustomClickAction-8]
	_ = x[ServerboundConfigAcceptCodeOfConduct-9]
	_ = x[ServerboundAcceptTeleportation-0]
	_ = x[ServerboundAttack-1]
	_ = x[ServerboundBlockEntityTagQuery-2]
	_ = x[ServerboundBundleItemSelected-3]
	_ = x[ServerboundChangeDifficulty-4]
	_ = x[ServerboundChangeGameMode-5]
	_ = x[ServerboundChatAck-6]
	_ = x[ServerboundChatCommand-7]
	_ = x[ServerboundChatCommandSigned-8]
	_ = x[ServerboundChat-9]
	_ = x[ServerboundChatSessionUpdate-10]
	_ = x[ServerboundChunkBatchReceived-11]
	_ = x[ServerboundClientCommand-12]
	_ = x[ServerboundClientTickEnd-13]
	_ = x[ServerboundClientInformation-14]
	_ = x[ServerboundCommandSuggestion-15]
	_ = x[ServerboundConfigurationAcknowledged-16]
	_ = x[ServerboundContainerButtonClick-17]
	_ = x[ServerboundContainerClick-18]
	_ = x[ServerboundContainerClose-19]
	_ = x[ServerboundContainerSlotStateChanged-20]
	_ = x[ServerboundCookieResponse-21]
	_ = x[ServerboundCustomPayload-22]
	_ = x[ServerboundDebugSubscriptionRequest-23]
	_ = x[ServerboundEditBook-24]
	_ = x[ServerboundEntityTagQuery-25]
	_ = x[ServerboundInteract-26]
	_ = x[ServerboundJigsawGenerate-27]
	_ = x[ServerboundKeepAlive-28]
	_ = x[ServerboundLockDifficulty-29]
	_ = x[ServerboundMovePlayerPos-30]
	_ = x[ServerboundMovePlayerPosRot-31]
	_ = x[ServerboundMovePlayerRot-32]
	_ = x[ServerboundMovePlayerStatusOnly-33]
	_ = x[ServerboundMoveVehicle-34]
	_ = x[ServerboundPaddleBoat-35]
	_ = x[ServerboundPickItemFromBlock-36]
	_ = x[ServerboundPickItemFromEntity-37]
	_ = x[ServerboundPingRequest-38]
	_ = x[ServerboundPlaceRecipe-39]
	_ = x[ServerboundPlayerAbilities-40]
	_ = x[ServerboundPlayerAction-41]
	_ = x[ServerboundPlayerCommand-42]
	_ = x[ServerboundPlayerInput-43]
	_ = x[ServerboundPlayerLoaded-44]
	_ = x[ServerboundPong-45]
	_ = x[ServerboundRecipeBookChangeSettings-46]
	_ = x[ServerboundRecipeBookSeenRecipe-47]
	_ = x[ServerboundRenameItem-48]
	_ = x[ServerboundResourcePack-49]
	_ = x[ServerboundSeenAdvancements-50]
	_ = x[ServerboundSelectTrade-51]
	_ = x[ServerboundSetBeacon-52]
	_ = x[ServerboundSetCarriedItem-53]
	_ = x[ServerboundSetCommandBlock-54]
	_ = x[ServerboundSetCommandMinecart-55]
	_ = x[ServerboundSetCreativeModeSlot-56]
	_ = x[ServerboundSetGameRule-57]
	_ = x[ServerboundSetJigsawBlock-58]
	_ = x[ServerboundSetStructureBlock-59]
	_ = x[ServerboundSetTestBlock-60]
	_ = x[ServerboundSignUpdate-61]
	_ = x[ServerboundSpectatorAction-62]
	_ = x[ServerboundSwing-63]
	_ = x[ServerboundTeleportToEntity-64]
	_ = x[ServerboundTestInstanceBlockAction-65]
	_ = x[ServerboundUseItemOn-66]
	_ = x[ServerboundUseItem-67]
	_ = x[ServerboundCustomClickAction-68]
	_ = x[ServerboundPacketIDGuard-69]
}

const _ServerboundPacketID_name = "ServerboundLoginHelloServerboundLoginKeyServerboundLoginCustomQueryAnswerServerboundLoginLoginAcknowledgedServerboundLoginCookieResponseServerboundConfigPongServerboundConfigResourcePackServerboundConfigSelectKnownPacksServerboundConfigCustomClickActionServerboundConfigAcceptCodeOfConductServerboundChatSessionUpdateServerboundChunkBatchReceivedServerboundClientCommandServerboundClientTickEndServerboundClientInformationServerboundCommandSuggestionServerboundConfigurationAcknowledgedServerboundContainerButtonClickServerboundContainerClickServerboundContainerCloseServerboundContainerSlotStateChangedServerboundCookieResponseServerboundCustomPayloadServerboundDebugSubscriptionRequestServerboundEditBookServerboundEntityTagQueryServerboundInteractServerboundJigsawGenerateServerboundKeepAliveServerboundLockDifficultyServerboundMovePlayerPosServerboundMovePlayerPosRotServerboundMovePlayerRotServerboundMovePlayerStatusOnlyServerboundMoveVehicleServerboundPaddleBoatServerboundPickItemFromBlockServerboundPickItemFromEntityServerboundPingRequestServerboundPlaceRecipeServerboundPlayerAbilitiesServerboundPlayerActionServerboundPlayerCommandServerboundPlayerInputServerboundPlayerLoadedServerboundPongServerboundRecipeBookChangeSettingsServerboundRecipeBookSeenRecipeServerboundRenameItemServerboundResourcePackServerboundSeenAdvancementsServerboundSelectTradeServerboundSetBeaconServerboundSetCarriedItemServerboundSetCommandBlockServerboundSetCommandMinecartServerboundSetCreativeModeSlotServerboundSetGameRuleServerboundSetJigsawBlockServerboundSetStructureBlockServerboundSetTestBlockServerboundSignUpdateServerboundSpectatorActionServerboundSwingServerboundTeleportToEntityServerboundTestInstanceBlockActionServerboundUseItemOnServerboundUseItemServerboundCustomClickActionServerboundPacketIDGuard"

var _ServerboundPacketID_index = [...]uint16{0, 21, 40, 73, 106, 136, 157, 186, 219, 253, 289, 317, 346, 370, 394, 422, 450, 486, 517, 542, 567, 603, 628, 652, 687, 706, 731, 750, 775, 795, 820, 844, 871, 895, 926, 948, 969, 997, 1026, 1048, 1070, 1096, 1119, 1143, 1165, 1188, 1203, 1238, 1269, 1290, 1313, 1340, 1362, 1382, 1407, 1433, 1462, 1492, 1514, 1539, 1567, 1590, 1611, 1637, 1653, 1680, 1714, 1734, 1752, 1780, 1804}

func (i ServerboundPacketID) String() string {
	if i < 0 || i >= ServerboundPacketID(len(_ServerboundPacketID_index)-1) {
		return "ServerboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerboundPacketID_name[_ServerboundPacketID_index[i]:_ServerboundPacketID_index[i+1]]
}
