// Code generated by "stringer -type ServerboundPacketID"; DO NOT EDIT.

package packetid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerboundLoginHello-0]
	_ = x[ServerboundLoginKey-1]
	_ = x[ServerboundLoginCustomQueryAnswer-2]
	_ = x[ServerboundLoginLoginAcknowledged-3]
	_ = x[ServerboundLoginCookieResponse-4]
	_ = x[ServerboundStatusStatusRequest-0]
	_ = x[ServerboundStatusPingRequest-1]
	_ = x[ServerboundConfigClientInformation-0]
	_ = x[ServerboundConfigCookieResponse-1]
	_ = x[ServerboundConfigCustomPayload-2]
	_ = x[ServerboundConfigFinishConfiguration-3]
	_ = x[ServerboundConfigKeepAlive-4]
	_ = x[ServerboundConfigPong-5]
	_ = x[ServerboundConfigResourcePack-6]
	_ = x[ServerboundConfigSelectKnownPacks-7]
	_ = x[ServerboundConfigCustomClickAction-8]
	_ = x[ServerboundConfigAcceptCodeOfConduct-9]
	_ = x[ServerboundAcceptTeleportation-0]
	_ = x[ServerboundBlockEntityTagQuery-1]
	_ = x[ServerboundBundleItemSelected-2]
	_ = x[ServerboundChangeDifficulty-3]
	_ = x[ServerboundChangeGameMode-4]
	_ = x[ServerboundChatAck-5]
	_ = x[ServerboundChatCommand-6]
	_ = x[ServerboundChatCommandSigned-7]
	_ = x[ServerboundChat-8]
	_ = x[ServerboundChatSessionUpdate-9]
	_ = x[ServerboundChunkBatchReceived-10]
	_ = x[ServerboundClientCommand-11]
	_ = x[ServerboundClientTickEnd-12]
	_ = x[ServerboundClientInformation-13]
	_ = x[ServerboundCommandSuggestion-14]
	_ = x[ServerboundConfigurationAcknowledged-15]
	_ = x[ServerboundContainerButtonClick-16]
	_ = x[ServerboundContainerClick-17]
	_ = x[ServerboundContainerClose-18]
	_ = x[ServerboundContainerSlotStateChanged-19]
	_ = x[ServerboundCookieResponse-20]
	_ = x[ServerboundCustomPayload-21]
	_ = x[ServerboundDebugSubscriptionRequest-22]
	_ = x[ServerboundEditBook-23]
	_ = x[ServerboundEntityTagQuery-24]
	_ = x[ServerboundInteract-25]
	_ = x[ServerboundJigsawGenerate-26]
	_ = x[ServerboundKeepAlive-27]
	_ = x[ServerboundLockDifficulty-28]
	_ = x[ServerboundMovePlayerPos-29]
	_ = x[ServerboundMovePlayerPosRot-30]
	_ = x[ServerboundMovePlayerRot-31]
	_ = x[ServerboundMovePlayerStatusOnly-32]
	_ = x[ServerboundMoveVehicle-33]
	_ = x[ServerboundPaddleBoat-34]
	_ = x[ServerboundPickItemFromBlock-35]
	_ = x[ServerboundPickItemFromEntity-36]
	_ = x[ServerboundPingRequest-37]
	_ = x[ServerboundPlaceRecipe-38]
	_ = x[ServerboundPlayerAbilities-39]
	_ = x[ServerboundPlayerAction-40]
	_ = x[ServerboundPlayerCommand-41]
	_ = x[ServerboundPlayerInput-42]
	_ = x[ServerboundPlayerLoaded-43]
	_ = x[ServerboundPong-44]
	_ = x[ServerboundRecipeBookChangeSettings-45]
	_ = x[ServerboundRecipeBookSeenRecipe-46]
	_ = x[ServerboundRenameItem-47]
	_ = x[ServerboundResourcePack-48]
	_ = x[ServerboundSeenAdvancements-49]
	_ = x[ServerboundSelectTrade-50]
	_ = x[ServerboundSetBeacon-51]
	_ = x[ServerboundSetCarriedItem-52]
	_ = x[ServerboundSetCommandBlock-53]
	_ = x[ServerboundSetCommandMinecart-54]
	_ = x[ServerboundSetCreativeModeSlot-55]
	_ = x[ServerboundSetJigsawBlock-56]
	_ = x[ServerboundSetStructureBlock-57]
	_ = x[ServerboundSetTestBlock-58]
	_ = x[ServerboundSignUpdate-59]
	_ = x[ServerboundSwing-60]
	_ = x[ServerboundTeleportToEntity-61]
	_ = x[ServerboundTestInstanceBlockAction-62]
	_ = x[ServerboundUseItemOn-63]
	_ = x[ServerboundUseItem-64]
	_ = x[ServerboundCustomClickAction-65]
	_ = x[ServerboundPacketIDGuard-66]
}

const _ServerboundPacketID_name = "ServerboundLoginHelloServerboundLoginKeyServerboundLoginCustomQueryAnswerServerboundLoginLoginAcknowledgedServerboundLoginCookieResponseServerboundConfigPongServerboundConfigResourcePackServerboundConfigSelectKnownPacksServerboundConfigCustomClickActionServerboundConfigAcceptCodeOfConductServerboundChunkBatchReceivedServerboundClientCommandServerboundClientTickEndServerboundClientInformationServerboundCommandSuggestionServerboundConfigurationAcknowledgedServerboundContainerButtonClickServerboundContainerClickServerboundContainerCloseServerboundContainerSlotStateChangedServerboundCookieResponseServerboundCustomPayloadServerboundDebugSubscriptionRequestServerboundEditBookServerboundEntityTagQueryServerboundInteractServerboundJigsawGenerateServerboundKeepAliveServerboundLockDifficultyServerboundMovePlayerPosServerboundMovePlayerPosRotServerboundMovePlayerRotServerboundMovePlayerStatusOnlyServerboundMoveVehicleServerboundPaddleBoatServerboundPickItemFromBlockServerboundPickItemFromEntityServerboundPingRequestServerboundPlaceRecipeServerboundPlayerAbilitiesServerboundPlayerActionServerboundPlayerCommandServerboundPlayerInputServerboundPlayerLoadedServerboundPongServerboundRecipeBookChangeSettingsServerboundRecipeBookSeenRecipeServerboundRenameItemServerboundResourcePackServerboundSeenAdvancementsServerboundSelectTradeServerboundSetBeaconServerboundSetCarriedItemServerboundSetCommandBlockServerboundSetCommandMinecartServerboundSetCreativeModeSlotServerboundSetJigsawBlockServerboundSetStructureBlockServerboundSetTestBlockServerboundSignUpdateServerboundSwingServerboundTeleportToEntityServerboundTestInstanceBlockActionServerboundUseItemOnServerboundUseItemServerboundCustomClickActionServerboundPacketIDGuard"

var _ServerboundPacketID_index = [...]uint16{0, 21, 40, 73, 106, 136, 157, 186, 219, 253, 289, 318, 342, 366, 394, 422, 458, 489, 514, 539, 575, 600, 624, 659, 678, 703, 722, 747, 767, 792, 816, 843, 867, 898, 920, 941, 969, 998, 1020, 1042, 1068, 1091, 1115, 1137, 1160, 1175, 1210, 1241, 1262, 1285, 1312, 1334, 1354, 1379, 1405, 1434, 1464, 1489, 1517, 1540, 1561, 1577, 1604, 1638, 1658, 1676, 1704, 1728}

func (i ServerboundPacketID) String() string {
	if i < 0 || i >= ServerboundPacketID(len(_ServerboundPacketID_index)-1) {
		return "ServerboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerboundPacketID_name[_ServerboundPacketID_index[i]:_ServerboundPacketID_index[i+1]]
}
