// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*AdditionalTradeCost)(nil)

type AdditionalTradeCost struct{ pk.VarInt }

func (AdditionalTradeCost) ID() string { return "minecraft:additional_trade_cost" }
