// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*AttackRange)(nil)

type AttackRange struct {
	MinRange         pk.Float
	MaxRange         pk.Float
	MinCreativeRange pk.Float
	MaxCreativeRange pk.Float
	HitboxMargin     pk.Float
	MobFactor        pk.Float
}

func (AttackRange) ID() string { return "minecraft:attack_range" }

func (a *AttackRange) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&a.MinRange,
		&a.MaxRange,
		&a.MinCreativeRange,
		&a.MaxCreativeRange,
		&a.HitboxMargin,
		&a.MobFactor,
	}.ReadFrom(r)
}

func (a *AttackRange) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&a.MinRange,
		&a.MaxRange,
		&a.MinCreativeRange,
		&a.MaxCreativeRange,
		&a.HitboxMargin,
		&a.MobFactor,
	}.WriteTo(w)
}
