// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*AttackRange)(nil)

type AttackRange struct {
	MinReach         pk.Float
	MaxReach         pk.Float
	MinCreativeReach pk.Float
	MaxCreativeReach pk.Float
	HitboxMargin     pk.Float
	MobFactor        pk.Float
}

func (AttackRange) ID() string { return "minecraft:attack_range" }

func (a *AttackRange) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&a.MinReach,
		&a.MaxReach,
		&a.MinCreativeReach,
		&a.MaxCreativeReach,
		&a.HitboxMargin,
		&a.MobFactor,
	}.ReadFrom(r)
}

func (a *AttackRange) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&a.MinReach,
		&a.MaxReach,
		&a.MinCreativeReach,
		&a.MaxCreativeReach,
		&a.HitboxMargin,
		&a.MobFactor,
	}.WriteTo(w)
}
