// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*BannerPatterns)(nil)

type BannerPatterns struct {
	Layers []BannerPatternLayer
}

func (BannerPatterns) ID() string { return "minecraft:banner_patterns" }

func (b *BannerPatterns) ReadFrom(r io.Reader) (int64, error) {
	return pk.Array(&b.Layers).ReadFrom(r)
}

func (b *BannerPatterns) WriteTo(w io.Writer) (int64, error) {
	return pk.Array(&b.Layers).WriteTo(w)
}
