// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*BaseColor)(nil)

type BaseColor struct{ pk.VarInt }

func (BaseColor) ID() string { return "minecraft:base_color" }
