// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Bees)(nil)

type Bees struct {
	Bees []BeeData
}

func (Bees) ID() string { return "minecraft:bees" }

func (b *Bees) ReadFrom(r io.Reader) (int64, error) {
	return pk.Array(&b.Bees).ReadFrom(r)
}

func (b *Bees) WriteTo(w io.Writer) (int64, error) {
	return pk.Array(&b.Bees).WriteTo(w)
}
