// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*BlockState)(nil)

type BlockState struct {
	Properties []BlockStateProperty
}

func (BlockState) ID() string { return "minecraft:block_state" }

func (b *BlockState) ReadFrom(r io.Reader) (int64, error) {
	return pk.Array(&b.Properties).ReadFrom(r)
}

func (b *BlockState) WriteTo(w io.Writer) (int64, error) {
	return pk.Array(&b.Properties).WriteTo(w)
}
