// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*BlocksAttacks)(nil)

type BlocksAttacks struct {
	BlockDelaySeconds    pk.Float
	DisableCooldownScale pk.Float
	DamageReductions     []DamageReduction
	ItemDamage           ItemDamageFunction
	BypassedBy           pk.Option[pk.String, *pk.String]
	BlockSound           pk.Option[SoundEvent, *SoundEvent]
	DisableSound         pk.Option[SoundEvent, *SoundEvent]
}

func (BlocksAttacks) ID() string { return "minecraft:blocks_attacks" }

func (b *BlocksAttacks) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&b.BlockDelaySeconds,
		&b.DisableCooldownScale,
		pk.Array(&b.DamageReductions),
		&b.ItemDamage,
		&b.BypassedBy,
		&b.BlockSound,
		&b.DisableSound,
	}.ReadFrom(r)
}

func (b *BlocksAttacks) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&b.BlockDelaySeconds,
		&b.DisableCooldownScale,
		pk.Array(&b.DamageReductions),
		&b.ItemDamage,
		&b.BypassedBy,
		&b.BlockSound,
		&b.DisableSound,
	}.WriteTo(w)
}
