// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"
)

var _ DataComponent = (*BreakSound)(nil)

type BreakSound struct {
	Sound SoundEvent
}

func (BreakSound) ID() string { return "minecraft:break_sound" }

func (b *BreakSound) ReadFrom(r io.Reader) (int64, error) {
	return b.Sound.ReadFrom(r)
}

func (b *BreakSound) WriteTo(w io.Writer) (int64, error) {
	return b.Sound.WriteTo(w)
}
