// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/nbt/dynbt"
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*BucketEntityData)(nil)

type BucketEntityData struct{ dynbt.Value }

func (BucketEntityData) ID() string { return "minecraft:bucket_entity_data" }

func (b *BucketEntityData) ReadFrom(r io.Reader) (int64, error) {
	return pk.NBT(&b.Value).ReadFrom(r)
}

func (b *BucketEntityData) WriteTo(w io.Writer) (int64, error) {
	return pk.NBT(&b.Value).WriteTo(w)
}
