// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*BundleContents)(nil)

type BundleContents struct {
	Contents []SlotData
}

func (BundleContents) ID() string { return "minecraft:bundle_contents" }

func (b *BundleContents) ReadFrom(r io.Reader) (int64, error) {
	return pk.Array(&b.Contents).ReadFrom(r)
}

func (b *BundleContents) WriteTo(w io.Writer) (int64, error) {
	return pk.Array(&b.Contents).WriteTo(w)
}
