// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*CatCollar)(nil)

type CatCollar struct{ pk.VarInt }

func (CatCollar) ID() string { return "minecraft:cat/collar" }
