// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*CatSoundVariant)(nil)

type CatSoundVariant struct{ pk.VarInt }

func (CatSoundVariant) ID() string { return "minecraft:cat/sound_variant" }
