// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*CatVariant)(nil)

type CatVariant struct{ pk.VarInt }

func (CatVariant) ID() string { return "minecraft:cat/variant" }
