// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*ChargedProjectiles)(nil)

type ChargedProjectiles struct {
	Projectiles []SlotData
}

func (ChargedProjectiles) ID() string { return "minecraft:charged_projectiles" }

func (c *ChargedProjectiles) ReadFrom(r io.Reader) (int64, error) {
	return pk.Array(&c.Projectiles).ReadFrom(r)
}

func (c *ChargedProjectiles) WriteTo(w io.Writer) (int64, error) {
	return pk.Array(&c.Projectiles).WriteTo(w)
}
