// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*ChickenSoundVariant)(nil)

type ChickenSoundVariant struct{ pk.VarInt }

func (ChickenSoundVariant) ID() string { return "minecraft:chicken/sound_variant" }
