// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*ChickenVariant)(nil)

type ChickenVariant struct{ pk.VarInt }

func (ChickenVariant) ID() string { return "minecraft:chicken/variant" }
