// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

var _ DataComponent = (*ChickenVariant)(nil)

type ChickenVariant struct{ EitherHolder }

func (ChickenVariant) ID() string { return "minecraft:chicken/variant" }
