// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Container)(nil)

type Container struct {
	Contents []SlotData
}

func (Container) ID() string { return "minecraft:container" }

func (c *Container) ReadFrom(r io.Reader) (int64, error) {
	return pk.Array(&c.Contents).ReadFrom(r)
}

func (c *Container) WriteTo(w io.Writer) (int64, error) {
	return pk.Array(&c.Contents).WriteTo(w)
}
