// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/nbt/dynbt"
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*ContainerLoot)(nil)

type ContainerLoot struct {
	Data dynbt.Value
}

func (ContainerLoot) ID() string { return "minecraft:container_loot" }

func (c *ContainerLoot) ReadFrom(r io.Reader) (int64, error) {
	return pk.NBTField{V: &c.Data, AllowUnknownFields: true}.ReadFrom(r)
}

func (c *ContainerLoot) WriteTo(w io.Writer) (int64, error) {
	return pk.NBTField{V: &c.Data, AllowUnknownFields: true}.WriteTo(w)
}
