// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*CowSoundVariant)(nil)

type CowSoundVariant struct{ pk.VarInt }

func (CowSoundVariant) ID() string { return "minecraft:cow/sound_variant" }
