// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*CowVariant)(nil)

type CowVariant struct{ pk.VarInt }

func (CowVariant) ID() string { return "minecraft:cow/variant" }
