// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"
)

var _ DataComponent = (*CreativeSlotLock)(nil)

type CreativeSlotLock struct{}

func (CreativeSlotLock) ID() string { return "minecraft:creative_slot_lock" }

func (c *CreativeSlotLock) ReadFrom(r io.Reader) (int64, error) { return 0, nil }

func (c *CreativeSlotLock) WriteTo(w io.Writer) (int64, error) { return 0, nil }
