// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*CustomModelData)(nil)

type CustomModelData struct {
	Floats  []pk.Float
	Flags   []pk.Boolean
	Strings []pk.String
	Colors  []pk.Int
}

func (CustomModelData) ID() string { return "minecraft:custom_model_data" }

func (c *CustomModelData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		pk.Array(&c.Floats),
		pk.Array(&c.Flags),
		pk.Array(&c.Strings),
		pk.Array(&c.Colors),
	}.ReadFrom(r)
}

func (c *CustomModelData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		pk.Array(&c.Floats),
		pk.Array(&c.Flags),
		pk.Array(&c.Strings),
		pk.Array(&c.Colors),
	}.WriteTo(w)
}
