// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/chat"
)

var _ DataComponent = (*CustomName)(nil)

type CustomName struct {
	Name chat.Message
}

func (CustomName) ID() string { return "minecraft:custom_name" }

func (c *CustomName) ReadFrom(r io.Reader) (int64, error) {
	return c.Name.ReadFrom(r)
}

func (c *CustomName) WriteTo(w io.Writer) (int64, error) {
	return c.Name.WriteTo(w)
}
