// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*DamageType)(nil)

type DamageType struct{ pk.VarInt }

func (DamageType) ID() string { return "minecraft:damage_type" }
