// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

var _ DataComponent = (*DamageResistant)(nil)

type DamageResistant struct{ IDSet }

func (DamageResistant) ID() string { return "minecraft:damage_resistant" }
