// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

var _ DataComponent = (*DamageType)(nil)

type DamageType struct{ EitherHolder }

func (DamageType) ID() string { return "minecraft:damage_type" }
