// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*DamageResistant)(nil)

type DamageResistant struct{ pk.String }

func (DamageResistant) ID() string { return "minecraft:damage_resistant" }
