// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Damage)(nil)

type Damage struct{ pk.VarInt }

func (Damage) ID() string { return "minecraft:damage" }
