// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/level/block"
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*DebugStickState)(nil)

type DebugStickState struct {
	Data block.State
}

func (DebugStickState) ID() string { return "minecraft:debug_stick_state" }

func (d *DebugStickState) ReadFrom(r io.Reader) (int64, error) {
	return pk.NBT(&d.Data).ReadFrom(r)
}

func (d *DebugStickState) WriteTo(w io.Writer) (int64, error) {
	return pk.NBT(&d.Data).WriteTo(w)
}
