// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Enchantments)(nil)

type Enchantments struct {
	Enchantments []EnchantmentEntry
}

func (Enchantments) ID() string { return "minecraft:enchantments" }

func (e *Enchantments) ReadFrom(r io.Reader) (int64, error) {
	return pk.Array(&e.Enchantments).ReadFrom(r)
}

func (e *Enchantments) WriteTo(w io.Writer) (int64, error) {
	return pk.Array(&e.Enchantments).WriteTo(w)
}
