// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*EnchantmentGlintOverride)(nil)

type EnchantmentGlintOverride struct {
	HasGlint pk.Boolean
}

func (EnchantmentGlintOverride) ID() string { return "minecraft:enchantment_glint_override" }

func (e *EnchantmentGlintOverride) ReadFrom(r io.Reader) (int64, error) {
	return e.HasGlint.ReadFrom(r)
}

func (e *EnchantmentGlintOverride) WriteTo(w io.Writer) (int64, error) {
	return e.HasGlint.WriteTo(w)
}
