// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Enchantable)(nil)

type Enchantable struct{ pk.VarInt }

func (Enchantable) ID() string { return "minecraft:enchantable" }
