// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/nbt/dynbt"
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*EntityData)(nil)

type EntityData struct {
	Type pk.VarInt
	Data dynbt.Value
}

func (EntityData) ID() string { return "minecraft:entity_data" }

func (e *EntityData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&e.Type,
		pk.NBTField{V: &e.Data, AllowUnknownFields: true},
	}.ReadFrom(r)
}

func (e *EntityData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&e.Type,
		pk.NBTField{V: &e.Data, AllowUnknownFields: true},
	}.WriteTo(w)
}
