// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Equippable)(nil)

type Equippable struct {
	Slot            pk.VarInt
	Sound           SoundEvent
	Model           pk.Option[pk.String, *pk.String]
	CameraOverlay   pk.Option[pk.String, *pk.String]
	AllowedEntities pk.Option[IDSet, *IDSet]
	Dispensable     pk.Boolean
	Swappable       pk.Boolean
	Damageable      pk.Boolean
	EquipOnInteract pk.Boolean
	Shearable       pk.Boolean
	ShearingSound   SoundEvent
}

func (Equippable) ID() string { return "minecraft:equippable" }

func (e *Equippable) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&e.Slot,
		&e.Sound,
		&e.Model,
		&e.CameraOverlay,
		&e.AllowedEntities,
		&e.Dispensable,
		&e.Swappable,
		&e.Damageable,
		&e.EquipOnInteract,
		&e.Shearable,
		&e.ShearingSound,
	}.ReadFrom(r)
}

func (e *Equippable) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&e.Slot,
		&e.Sound,
		&e.Model,
		&e.CameraOverlay,
		&e.AllowedEntities,
		&e.Dispensable,
		&e.Swappable,
		&e.Damageable,
		&e.EquipOnInteract,
		&e.Shearable,
		&e.ShearingSound,
	}.WriteTo(w)
}
