// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Fireworks)(nil)

type Fireworks struct {
	FlightDuration pk.VarInt
	Explosions     []ItemFireworkExplosion
}

func (Fireworks) ID() string { return "minecraft:fireworks" }

func (f *Fireworks) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&f.FlightDuration,
		pk.Array(&f.Explosions),
	}.ReadFrom(r)
}

func (f *Fireworks) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&f.FlightDuration,
		pk.Array(&f.Explosions),
	}.WriteTo(w)
}
