// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

var _ DataComponent = (*FireworkExplosion)(nil)

type FireworkExplosion struct{ ItemFireworkExplosion }

func (FireworkExplosion) ID() string { return "minecraft:firework_explosion" }
