// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Food)(nil)

type Food struct {
	Nutrition    pk.VarInt
	Saturation   pk.Float
	CanAlwaysEat pk.Boolean
}

func (Food) ID() string { return "minecraft:food" }

func (f *Food) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&f.Nutrition,
		&f.Saturation,
		&f.CanAlwaysEat,
	}.ReadFrom(r)
}

func (f *Food) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&f.Nutrition,
		&f.Saturation,
		&f.CanAlwaysEat,
	}.WriteTo(w)
}
