// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*FoxVariant)(nil)

type FoxVariant struct{ pk.VarInt }

func (FoxVariant) ID() string { return "minecraft:fox/variant" }
