// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"
)

var _ DataComponent = (*Glider)(nil)

type Glider struct{}

func (Glider) ID() string { return "minecraft:glider" }

func (g *Glider) ReadFrom(r io.Reader) (int64, error) { return 0, nil }

func (g *Glider) WriteTo(w io.Writer) (int64, error) { return 0, nil }
