// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/chat"
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Instrument)(nil)

type InstrumentData struct {
	SoundEvent  SoundEvent
	UseDuration pk.Float
	Range       pk.Float
	Description chat.Message
}

func (i *InstrumentData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&i.SoundEvent, &i.UseDuration, &i.Range, &i.Description}.ReadFrom(r)
}

func (i InstrumentData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{&i.SoundEvent, &i.UseDuration, &i.Range, &i.Description}.WriteTo(w)
}

type Instrument struct {
	HasHolder  pk.Boolean
	HolderType pk.VarInt
	InlineData InstrumentData
	TagKey     pk.String
}

func (Instrument) ID() string { return "minecraft:instrument" }

func (i *Instrument) ReadFrom(r io.Reader) (n int64, err error) {
	n, err = i.HasHolder.ReadFrom(r)
	if err != nil {
		return
	}
	if i.HasHolder {
		n2, err := i.HolderType.ReadFrom(r)
		n += n2
		if err != nil {
			return n, err
		}
		if i.HolderType == 0 {
			n2, err = i.InlineData.ReadFrom(r)
			n += n2
		}
		return n, err
	}
	n2, err := i.TagKey.ReadFrom(r)
	return n + n2, err
}

func (i *Instrument) WriteTo(w io.Writer) (n int64, err error) {
	n, err = i.HasHolder.WriteTo(w)
	if err != nil {
		return
	}
	if i.HasHolder {
		n2, err := i.HolderType.WriteTo(w)
		n += n2
		if err != nil {
			return n, err
		}
		if i.HolderType == 0 {
			n2, err = i.InlineData.WriteTo(w)
			n += n2
		}
		return n, err
	}
	n2, err := i.TagKey.WriteTo(w)
	return n + n2, err
}
