// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/chat"
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Instrument)(nil)

type InstrumentData struct {
	SoundEvent  SoundEvent
	UseDuration pk.Float
	Range       pk.Float
	Description chat.Message
}

func (i *InstrumentData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&i.SoundEvent, &i.UseDuration, &i.Range, &i.Description}.ReadFrom(r)
}

func (i InstrumentData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{&i.SoundEvent, &i.UseDuration, &i.Range, &i.Description}.WriteTo(w)
}

type Instrument struct {
	Type       pk.VarInt
	InlineData InstrumentData
}

func (Instrument) ID() string { return "minecraft:instrument" }

func (i *Instrument) ReadFrom(r io.Reader) (n int64, err error) {
	n, err = i.Type.ReadFrom(r)
	if err != nil {
		return
	}
	if i.Type == 0 {
		n2, err := i.InlineData.ReadFrom(r)
		n += n2
		return n, err
	}
	return
}

func (i *Instrument) WriteTo(w io.Writer) (n int64, err error) {
	n, err = i.Type.WriteTo(w)
	if err != nil {
		return
	}
	if i.Type == 0 {
		n2, err := i.InlineData.WriteTo(w)
		n += n2
		return n, err
	}
	return
}
