// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"
)

var _ DataComponent = (*IntangibleProjectile)(nil)

type IntangibleProjectile struct{}

func (IntangibleProjectile) ID() string { return "minecraft:intangible_projectile" }

func (i *IntangibleProjectile) ReadFrom(r io.Reader) (int64, error) { return 0, nil }

func (i *IntangibleProjectile) WriteTo(w io.Writer) (int64, error) { return 0, nil }
