// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*ItemModel)(nil)

type ItemModel struct{ pk.String }

func (ItemModel) ID() string { return "minecraft:item_model" }
