// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/chat"
)

var _ DataComponent = (*ItemName)(nil)

type ItemName struct {
	Name chat.Message
}

func (ItemName) ID() string { return "minecraft:item_name" }

func (i *ItemName) ReadFrom(r io.Reader) (int64, error) {
	return i.Name.ReadFrom(r)
}

func (i *ItemName) WriteTo(w io.Writer) (int64, error) {
	return i.Name.WriteTo(w)
}
