// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/chat"
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*JukeboxPlayable)(nil)

type JukeboxSongData struct {
	SoundEvent       SoundEvent
	Description      chat.Message
	LengthInSeconds  pk.Float
	ComparatorOutput pk.VarInt
}

func (j *JukeboxSongData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&j.SoundEvent, &j.Description, &j.LengthInSeconds, &j.ComparatorOutput}.ReadFrom(r)
}

func (j JukeboxSongData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{&j.SoundEvent, &j.Description, &j.LengthInSeconds, &j.ComparatorOutput}.WriteTo(w)
}

type JukeboxPlayable struct {
	Type       pk.VarInt
	InlineData JukeboxSongData
}

func (JukeboxPlayable) ID() string { return "minecraft:jukebox_playable" }

func (j *JukeboxPlayable) ReadFrom(r io.Reader) (n int64, err error) {
	n, err = j.Type.ReadFrom(r)
	if err != nil {
		return
	}
	if j.Type == 0 {
		n2, err := j.InlineData.ReadFrom(r)
		n += n2
		return n, err
	}
	return
}

func (j *JukeboxPlayable) WriteTo(w io.Writer) (n int64, err error) {
	n, err = j.Type.WriteTo(w)
	if err != nil {
		return
	}
	if j.Type == 0 {
		n2, err := j.InlineData.WriteTo(w)
		n += n2
		return n, err
	}
	return
}
