// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*KineticWeapon)(nil)

type KineticWeapon struct {
	ContactCooldownTicks pk.VarInt
	DelayTicks           pk.VarInt
	DismountConditions   pk.Option[KineticWeaponCondition, *KineticWeaponCondition]
	KnockbackConditions  pk.Option[KineticWeaponCondition, *KineticWeaponCondition]
	DamageConditions     pk.Option[KineticWeaponCondition, *KineticWeaponCondition]
	ForwardMovement      pk.Float
	DamageMultiplier     pk.Float
	Sound                pk.Option[SoundEvent, *SoundEvent]
	HitSound             pk.Option[SoundEvent, *SoundEvent]
}

func (KineticWeapon) ID() string { return "minecraft:kinetic_weapon" }

func (k *KineticWeapon) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&k.ContactCooldownTicks,
		&k.DelayTicks,
		&k.DismountConditions,
		&k.KnockbackConditions,
		&k.DamageConditions,
		&k.ForwardMovement,
		&k.DamageMultiplier,
		&k.Sound,
		&k.HitSound,
	}.ReadFrom(r)
}

func (k *KineticWeapon) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&k.ContactCooldownTicks,
		&k.DelayTicks,
		&k.DismountConditions,
		&k.KnockbackConditions,
		&k.DamageConditions,
		&k.ForwardMovement,
		&k.DamageMultiplier,
		&k.Sound,
		&k.HitSound,
	}.WriteTo(w)
}
