// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*LlamaVariant)(nil)

type LlamaVariant struct{ pk.VarInt }

func (LlamaVariant) ID() string { return "minecraft:llama/variant" }
