// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/nbt/dynbt"
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Lock)(nil)

type Lock struct {
	Data dynbt.Value
}

func (Lock) ID() string { return "minecraft:lock" }

func (l *Lock) ReadFrom(r io.Reader) (int64, error) {
	return pk.NBTField{V: &l.Data, AllowUnknownFields: true}.ReadFrom(r)
}

func (l *Lock) WriteTo(w io.Writer) (int64, error) {
	return pk.NBTField{V: &l.Data, AllowUnknownFields: true}.WriteTo(w)
}
