// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*LodestoneTracker)(nil)

type LodestoneTracker struct {
	GlobalPosition pk.Option[GlobalPos, *GlobalPos]
	Tracked        pk.Boolean
}

func (LodestoneTracker) ID() string { return "minecraft:lodestone_tracker" }

func (l *LodestoneTracker) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&l.GlobalPosition,
		&l.Tracked,
	}.ReadFrom(r)
}

func (l *LodestoneTracker) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&l.GlobalPosition,
		&l.Tracked,
	}.WriteTo(w)
}
