// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/chat"
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Lore)(nil)

type Lore struct {
	Lines []chat.Message
}

func (Lore) ID() string { return "minecraft:lore" }

func (l *Lore) ReadFrom(r io.Reader) (int64, error) {
	return pk.Array(&l.Lines).ReadFrom(r)
}

func (l *Lore) WriteTo(w io.Writer) (int64, error) {
	return pk.Array(&l.Lines).WriteTo(w)
}
