// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*MaxDamage)(nil)

type MaxDamage struct{ pk.VarInt }

func (MaxDamage) ID() string { return "minecraft:max_damage" }
