// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*MaxStackSize)(nil)

type MaxStackSize struct{ pk.VarInt }

func (MaxStackSize) ID() string { return "minecraft:max_stack_size" }
