// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*MooshroomVariant)(nil)

type MooshroomVariant struct{ pk.VarInt }

func (MooshroomVariant) ID() string { return "minecraft:mooshroom/variant" }
