// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*NoteBlockSound)(nil)

type NoteBlockSound struct{ pk.String }

func (NoteBlockSound) ID() string { return "minecraft:note_block_sound" }
