// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*OminousBottleAmplifier)(nil)

type OminousBottleAmplifier struct{ pk.VarInt }

func (OminousBottleAmplifier) ID() string { return "minecraft:ominous_bottle_amplifier" }
