// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/chat"
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*PaintingVariant)(nil)

type PaintingVariantData struct {
	Width   pk.VarInt
	Height  pk.VarInt
	AssetID pk.String
	Title   pk.Option[chat.Message, *chat.Message]
	Author  pk.Option[chat.Message, *chat.Message]
}

func (p *PaintingVariantData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Width, &p.Height, &p.AssetID, &p.Title, &p.Author}.ReadFrom(r)
}

func (p PaintingVariantData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{&p.Width, &p.Height, &p.AssetID, &p.Title, &p.Author}.WriteTo(w)
}

type PaintingVariant struct {
	Type       pk.VarInt
	InlineData PaintingVariantData
}

func (PaintingVariant) ID() string { return "minecraft:painting/variant" }

func (p *PaintingVariant) ReadFrom(r io.Reader) (n int64, err error) {
	n, err = p.Type.ReadFrom(r)
	if err != nil {
		return
	}
	if p.Type == 0 {
		n2, err := p.InlineData.ReadFrom(r)
		n += n2
		return n, err
	}
	return
}

func (p *PaintingVariant) WriteTo(w io.Writer) (n int64, err error) {
	n, err = p.Type.WriteTo(w)
	if err != nil {
		return
	}
	if p.Type == 0 {
		n2, err := p.InlineData.WriteTo(w)
		n += n2
		return n, err
	}
	return
}
