// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*ParrotVariant)(nil)

type ParrotVariant struct{ pk.VarInt }

func (ParrotVariant) ID() string { return "minecraft:parrot/variant" }
