// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*PiercingWeapon)(nil)

type PiercingWeapon struct {
	DealsKnockback pk.Boolean
	Dismounts      pk.Boolean
	Sound          pk.Option[SoundEvent, *SoundEvent]
	HitSound       pk.Option[SoundEvent, *SoundEvent]
}

func (PiercingWeapon) ID() string { return "minecraft:piercing_weapon" }

func (p *PiercingWeapon) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&p.DealsKnockback,
		&p.Dismounts,
		&p.Sound,
		&p.HitSound,
	}.ReadFrom(r)
}

func (p *PiercingWeapon) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&p.DealsKnockback,
		&p.Dismounts,
		&p.Sound,
		&p.HitSound,
	}.WriteTo(w)
}
