// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*PigSoundVariant)(nil)

type PigSoundVariant struct{ pk.VarInt }

func (PigSoundVariant) ID() string { return "minecraft:pig/sound_variant" }
