// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*PigVariant)(nil)

type PigVariant struct{ pk.VarInt }

func (PigVariant) ID() string { return "minecraft:pig/variant" }
