// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*PotDecorations)(nil)

type PotDecorations struct {
	Decorations []pk.VarInt
}

func (PotDecorations) ID() string { return "minecraft:pot_decorations" }

func (p *PotDecorations) ReadFrom(r io.Reader) (int64, error) {
	return pk.Array(&p.Decorations).ReadFrom(r)
}

func (p *PotDecorations) WriteTo(w io.Writer) (int64, error) {
	return pk.Array(&p.Decorations).WriteTo(w)
}
