// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*PotionDurationScale)(nil)

type PotionDurationScale struct{ pk.Float }

func (PotionDurationScale) ID() string { return "minecraft:potion_duration_scale" }
