// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

var _ DataComponent = (*ProvidesBannerPatterns)(nil)

type ProvidesBannerPatterns struct{ IDSet }

func (ProvidesBannerPatterns) ID() string { return "minecraft:provides_banner_patterns" }
