// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*ProvidesBannerPatterns)(nil)

type ProvidesBannerPatterns struct{ pk.String }

func (ProvidesBannerPatterns) ID() string { return "minecraft:provides_banner_patterns" }
