// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*ProvidesTrimMaterial)(nil)

type ProvidesTrimMaterial struct {
	Type       pk.VarInt
	InlineData ArmorTrimMaterial
}

func (ProvidesTrimMaterial) ID() string { return "minecraft:provides_trim_material" }

func (p *ProvidesTrimMaterial) ReadFrom(r io.Reader) (n int64, err error) {
	n, err = p.Type.ReadFrom(r)
	if err != nil {
		return
	}
	if p.Type == 0 {
		n2, err := p.InlineData.ReadFrom(r)
		n += n2
		return n, err
	}
	return
}

func (p *ProvidesTrimMaterial) WriteTo(w io.Writer) (n int64, err error) {
	n, err = p.Type.WriteTo(w)
	if err != nil {
		return
	}
	if p.Type == 0 {
		n2, err := p.InlineData.WriteTo(w)
		n += n2
		return n, err
	}
	return
}
