// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*ProvidesTrimMaterial)(nil)

type ProvidesTrimMaterial struct {
	HasHolder  pk.Boolean
	HolderType pk.VarInt
	InlineData ArmorTrimMaterial
	TagKey     pk.String
}

func (ProvidesTrimMaterial) ID() string { return "minecraft:provides_trim_material" }

func (p *ProvidesTrimMaterial) ReadFrom(r io.Reader) (n int64, err error) {
	n, err = p.HasHolder.ReadFrom(r)
	if err != nil {
		return
	}
	if p.HasHolder {
		n2, err := p.HolderType.ReadFrom(r)
		n += n2
		if err != nil {
			return n, err
		}
		if p.HolderType == 0 {
			n2, err = p.InlineData.ReadFrom(r)
			n += n2
		}
		return n, err
	}
	n2, err := p.TagKey.ReadFrom(r)
	return n + n2, err
}

func (p *ProvidesTrimMaterial) WriteTo(w io.Writer) (n int64, err error) {
	n, err = p.HasHolder.WriteTo(w)
	if err != nil {
		return
	}
	if p.HasHolder {
		n2, err := p.HolderType.WriteTo(w)
		n += n2
		if err != nil {
			return n, err
		}
		if p.HolderType == 0 {
			n2, err = p.InlineData.WriteTo(w)
			n += n2
		}
		return n, err
	}
	n2, err := p.TagKey.WriteTo(w)
	return n + n2, err
}
