// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	"github.com/Tnze/go-mc/nbt/dynbt"
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Recipes)(nil)

type Recipes struct {
	Data dynbt.Value
}

func (Recipes) ID() string { return "minecraft:recipes" }

func (e *Recipes) ReadFrom(r io.Reader) (int64, error) {
	return pk.NBT(&e.Data).ReadFrom(r)
}

func (e *Recipes) WriteTo(w io.Writer) (int64, error) {
	return pk.NBT(&e.Data).WriteTo(w)
}
