// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*SalmonSize)(nil)

type SalmonSize struct{ pk.VarInt }

func (SalmonSize) ID() string { return "minecraft:salmon/size" }
