// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*SheepColor)(nil)

type SheepColor struct{ pk.VarInt }

func (SheepColor) ID() string { return "minecraft:sheep/color" }
