// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*StoredEnchantments)(nil)

type StoredEnchantments struct {
	Enchantments []EnchantmentEntry
}

func (StoredEnchantments) ID() string { return "minecraft:stored_enchantments" }

func (s *StoredEnchantments) ReadFrom(r io.Reader) (int64, error) {
	return pk.Array(&s.Enchantments).ReadFrom(r)
}

func (s *StoredEnchantments) WriteTo(w io.Writer) (int64, error) {
	return pk.Array(&s.Enchantments).WriteTo(w)
}
