// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

var _ DataComponent = (*SulfurCubeContent)(nil)

type SulfurCubeContent struct{ ItemStackTemplate }

func (SulfurCubeContent) ID() string { return "minecraft:sulfur_cube_content" }
