// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*SuspiciousStewEffects)(nil)

type SuspiciousStewEffects struct {
	Effects []StewEffect
}

func (SuspiciousStewEffects) ID() string { return "minecraft:suspicious_stew_effects" }

func (s *SuspiciousStewEffects) ReadFrom(r io.Reader) (int64, error) {
	return pk.Array(&s.Effects).ReadFrom(r)
}

func (s *SuspiciousStewEffects) WriteTo(w io.Writer) (int64, error) {
	return pk.Array(&s.Effects).WriteTo(w)
}
