// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*SwingAnimation)(nil)

type SwingAnimation struct {
	Type     pk.VarInt
	Duration pk.VarInt
}

func (SwingAnimation) ID() string { return "minecraft:swing_animation" }

func (s *SwingAnimation) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&s.Type,
		&s.Duration,
	}.ReadFrom(r)
}

func (s *SwingAnimation) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&s.Type,
		&s.Duration,
	}.WriteTo(w)
}
