// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*TooltipDisplay)(nil)

type TooltipDisplay struct {
	HideTooltip      pk.Boolean
	HiddenComponents []pk.VarInt
}

func (TooltipDisplay) ID() string { return "minecraft:tooltip_display" }

func (t *TooltipDisplay) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&t.HideTooltip,
		pk.Array(&t.HiddenComponents),
	}.ReadFrom(r)
}

func (t *TooltipDisplay) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&t.HideTooltip,
		pk.Array(&t.HiddenComponents),
	}.WriteTo(w)
}
