// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Tool)(nil)

type Tool struct {
	Rules                      []ToolRule
	DefaultMiningSpeed         pk.Float
	DamagePerBlock             pk.VarInt
	CanDestroyBlocksInCreative pk.Boolean
}

func (Tool) ID() string { return "minecraft:tool" }

func (t *Tool) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		pk.Array(&t.Rules),
		&t.DefaultMiningSpeed,
		&t.DamagePerBlock,
		&t.CanDestroyBlocksInCreative,
	}.ReadFrom(r)
}

func (t *Tool) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		pk.Array(&t.Rules),
		&t.DefaultMiningSpeed,
		&t.DamagePerBlock,
		&t.CanDestroyBlocksInCreative,
	}.WriteTo(w)
}
