// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Trim)(nil)

type Trim struct {
	MaterialType pk.VarInt
	MaterialData ArmorTrimMaterial
	PatternType  pk.VarInt
	PatternData  ArmorTrimPattern
}

func (Trim) ID() string { return "minecraft:trim" }

func (t *Trim) ReadFrom(r io.Reader) (n int64, err error) {
	return pk.Tuple{
		&t.MaterialType,
		pk.Opt{
			Has:   func() bool { return t.MaterialType == 0 },
			Field: &t.MaterialData,
		},
		&t.PatternType,
		pk.Opt{
			Has:   func() bool { return t.PatternType == 0 },
			Field: &t.PatternData,
		},
	}.ReadFrom(r)
}

func (t *Trim) WriteTo(w io.Writer) (n int64, err error) {
	return pk.Tuple{
		&t.MaterialType,
		pk.Opt{
			Has:   func() bool { return t.MaterialType == 0 },
			Field: &t.MaterialData,
		},
		&t.PatternType,
		pk.Opt{
			Has:   func() bool { return t.PatternType == 0 },
			Field: &t.PatternData,
		},
	}.WriteTo(w)
}
