// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*TropicalFishBaseColor)(nil)

type TropicalFishBaseColor struct{ pk.VarInt }

func (TropicalFishBaseColor) ID() string { return "minecraft:tropical_fish/base_color" }
