// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*TropicalFishPattern)(nil)

type TropicalFishPattern struct{ pk.VarInt }

func (TropicalFishPattern) ID() string { return "minecraft:tropical_fish/pattern" }
