// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"
)

var _ DataComponent = (*Unbreakable)(nil)

type Unbreakable struct{}

func (Unbreakable) ID() string { return "minecraft:unbreakable" }

func (u *Unbreakable) ReadFrom(r io.Reader) (int64, error) { return 0, nil }

func (u *Unbreakable) WriteTo(w io.Writer) (int64, error) { return 0, nil }
