// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*UseCooldown)(nil)

type UseCooldown struct {
	Seconds       pk.Float
	CooldownGroup pk.Option[pk.String, *pk.String]
}

func (UseCooldown) ID() string { return "minecraft:use_cooldown" }

func (u *UseCooldown) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&u.Seconds,
		&u.CooldownGroup,
	}.ReadFrom(r)
}

func (u *UseCooldown) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&u.Seconds,
		&u.CooldownGroup,
	}.WriteTo(w)
}
