// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*UseEffects)(nil)

type UseEffects struct {
	CanSprint          pk.Boolean
	InteractVibrations pk.Boolean
	SpeedMultiplier    pk.Float
}

func (UseEffects) ID() string { return "minecraft:use_effects" }

func (u *UseEffects) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&u.CanSprint,
		&u.InteractVibrations,
		&u.SpeedMultiplier,
	}.ReadFrom(r)
}

func (u *UseEffects) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&u.CanSprint,
		&u.InteractVibrations,
		&u.SpeedMultiplier,
	}.WriteTo(w)
}
