// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"
)

var _ DataComponent = (*UseRemainder)(nil)

type UseRemainder struct {
	Remainder SlotData
}

func (UseRemainder) ID() string { return "minecraft:use_remainder" }

func (u *UseRemainder) ReadFrom(r io.Reader) (int64, error) {
	return u.Remainder.ReadFrom(r)
}

func (u *UseRemainder) WriteTo(w io.Writer) (int64, error) {
	return u.Remainder.WriteTo(w)
}
