// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*VillagerVariant)(nil)

type VillagerVariant struct{ pk.VarInt }

func (VillagerVariant) ID() string { return "minecraft:villager/variant" }
