// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*Weapon)(nil)

type Weapon struct {
	ItemDamagePerAttack       pk.VarInt
	DisableBlockingForSeconds pk.Float
}

func (Weapon) ID() string { return "minecraft:weapon" }

func (e *Weapon) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&e.ItemDamagePerAttack,
		&e.DisableBlockingForSeconds,
	}.ReadFrom(r)
}

func (e *Weapon) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&e.ItemDamagePerAttack,
		&e.DisableBlockingForSeconds,
	}.WriteTo(w)
}
