// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*WolfCollar)(nil)

type WolfCollar struct{ pk.VarInt }

func (WolfCollar) ID() string { return "minecraft:wolf/collar" }
