// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*WolfVariant)(nil)

type WolfVariant struct{ pk.VarInt }

func (WolfVariant) ID() string { return "minecraft:wolf/variant" }
