// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*WritableBookContent)(nil)

type WritableBookContent struct {
	Pages []Page
}

func (WritableBookContent) ID() string { return "minecraft:writable_book_content" }

func (x *WritableBookContent) ReadFrom(r io.Reader) (int64, error) {
	return pk.Array(&x.Pages).ReadFrom(r)
}

func (x *WritableBookContent) WriteTo(w io.Writer) (int64, error) {
	return pk.Array(&x.Pages).WriteTo(w)
}
