// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*WrittenBookContent)(nil)

type WrittenBookContent struct {
	RawTitle      pk.String
	FilteredTitle pk.Option[pk.String, *pk.String]
	Author        pk.String
	Generation    pk.VarInt
	Pages         []WrittenPage
	Resolved      pk.Boolean
}

func (WrittenBookContent) ID() string { return "minecraft:written_book_content" }

func (x *WrittenBookContent) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&x.RawTitle,
		&x.FilteredTitle,
		&x.Author,
		&x.Generation,
		pk.Array(&x.Pages),
		&x.Resolved,
	}.ReadFrom(r)
}

func (x *WrittenBookContent) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&x.RawTitle,
		&x.FilteredTitle,
		&x.Author,
		&x.Generation,
		pk.Array(&x.Pages),
		&x.Resolved,
	}.WriteTo(w)
}
