// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/Tnze/go-mc/net/packet"
)

var _ DataComponent = (*ZombieNautilusVariant)(nil)

type ZombieNautilusVariant struct{ pk.VarInt }

func (ZombieNautilusVariant) ID() string { return "minecraft:zombie_nautilus/variant" }
