// Code generated by tools/gen_component_types.go from hand-crafted/component_schema.json; DO NOT EDIT.
package component

var _ DataComponent = (*ZombieNautilusVariant)(nil)

type ZombieNautilusVariant struct{ EitherHolder }

func (ZombieNautilusVariant) ID() string { return "minecraft:zombie_nautilus/variant" }
